### ISSUE TITLE
Регулятор громкости

### ISSUE THREAD

**Issue by clsv** [dzhard/YandexMusicFirefoxControls#1]
Проблема при попытке изменить громкость, не успеваешь навести мышку на регулятор...
Если не сложно добавьте событие на скролл.

Спасибо за хорошее расширение!

**Comment by dzhard** [comment]
Спасибо за совет. На linux скролл расположен правильно, тем не менее опустил его и проверил на windows, также добавил событие на скролл.
#2

**Comment by dzhard** [comment]
Новая версия отправлена на валидацию, появится в ближайшее время

**Comment by clsv** [comment]
Спасибо за фиксы, проблема как раз была на линуксе. теперь все отлично!
