### ISSUE TITLE
Previos button is enabled despite controlState for prev:false

### ISSUE THREAD

**Issue by RachokGenious** [dzhard/YandexMusicFirefoxControls#11]
![Screenshot from 2020-02-06 01-02-52](https://user-images.githubusercontent.com/10640804/73887861-80f6ef00-487d-11ea-9309-6b30de9c26e1.png)

**Comment by dzhard** [comment]
Fixed in [https://github.com/dzhard/YandexMusicFirefoxControls/commit/0deacb015a22c6e4bffe4714ce7b5d0c1ea366a3](url)
