### ISSUE TITLE
Поддержка других доменов Я.Музыки

### ISSUE THREAD

**Issue by glebliutsko** [dzhard/YandexMusicFirefoxControls#7]
Сейчас расширение поддреживает только 2 домена:
 - [music.yandex.ru](https://music.yandex.ru/home)
 - [music.yandex.by](https://music.yandex.by/home)

Предлагаю добавить поддержку других доменов:
 - [music.yandex.com](https://music.yandex.com/home)
 - [music.yandex.kz](https://music.yandex.kz/home)
 - [music.yandex.ua](https://music.yandex.ua/home)

**Comment by dzhard** [comment]
Добавлено в версии 1.1.1
